### ISSUE TITLE
typo in done1 and done2 console log

### ISSUE THREAD

**Issue by SynthWeaver** [besoeasy/nanopay#1]
Currently:

        //recieve pending transactions
	var done1 = await nano.fetchPending(secrateKey);

	if (done1.hash) {
		console.log('fetched : ' + done.hash);
	}

          // send nano to address
	var done2 = await nano.send(secrateKey, nanoaddress, amount);

	if (done2.hash) {
		console.log('sent : ' + done.hash);
	}

should be:

```
//recieve pending transactions
var done1 = await nano.fetchPending(secrateKey);

if (done1.hash) {
console.log('fetched : ' + done1.hash);
}

        // send nano to address
var done2 = await nano.send(secrateKey, nanoaddress, amount);

if (done2.hash) {
console.log('sent : ' + done2.hash);
}
```

**Comment by besoeasy** [comment]
yes
