### ISSUE TITLE
PoW pre rendering idea

### ISSUE THREAD

**Issue by SynthWeaver** [besoeasy/nanopay#2]
Hi Besoeasy,
First of all I want to thank you for this piece of code, I have a blast playing with nano and code at the same time. It also helps that your code is very readable.

I created a function that allows you to create and store a new PoW at the start of the application and each time you spend the old PoW and need a new one. This saves some time for the end user because generating a PoW can take some time. It is not finished, and not perfect, but I do want to share it with you.

```
setTimeout(() => {
	generatePow(secrateKey);
}, 1000);

var pow = null;
async function generatePow(secretKey) {
	var address = await secretKeytoaddr(secretKey);
	var sddsf_address = await accountdig(address);
	var previous = sddsf_address.frontier;
	console.log("generating PoW")
	pow = await hybirdWork(previous);
	console.log("PoW ready");
}

async function send(secretKey, sendto, amount) {
	
        if(pow == null){
		console.log("PoW not ready yet")
		return;
	}

        ...

	generatePow(secretKey);

	return retr;
}
```

**Comment by besoeasy** [comment]
thank you, i had the same concept being used on my casino but I removed it for atomicity!



`
async function workcpugpu(blockblock) {
  console.log("work requested : " + blockblock);

  return axios
    .post("https://bpow.banano.cc/service/", {
      user: "xxx",
      api_key: "xxxx",
      action: "work_generate",
      difficulty: "fffffff800000000",
      hash: blockblock,
    })
    .then(async function (response) {
      console.log("gpu work : " + response.data.work);

      if (typeof response.data.work === "undefined") {
        pow = await nanocurrency.computeWork(
          blockblock,
          (ComputeWorkParams = { workThreshold: "fffffff800000000" })
        );
        console.log("cpu work : " + pow);
        return pow;
      } else {
        return response.data.work;
      }
    })
    .catch(async function (error) {
      console.log(error);

      pow = await nanocurrency.computeWork(
        blockblock,
        (ComputeWorkParams = { workThreshold: "fffffff800000000" })
      );
      console.log("cpu work : " + pow);
      return pow;
    });
}`
